
import image1 from './assets/b-11.jpg.jpg';
import image2 from './assets/b-11.jpg (2).jpg';
import image3 from './assets/b-11.jpg (3).jpg';
import image4 from './assets/b-11.jpg (4).jpg';
import image5 from './assets/b-11.jpg (5).jpg';
import image6 from './assets/b-11.jpg (6).jpg';
import image7 from './assets/b-11.jpg (7).jpg';
import image8 from './assets/b-11.jpg (8).jpg';
import image9 from './assets/b-11.jpg (9).jpg';

// ========================================================
import Icon1 from './assets/Icon (2).svg';
import video from './assets/Vector (3).svg';
import Image from './assets/Vector (4).svg';
import location from './assets/Icon (3).svg';
import bed from './assets/Vector (5).svg';
import toilet from './assets/Icon (4).svg';
import arrow from './assets/Vector (6).svg';
import share from './assets/Icon (5).svg';
import link from './assets/Link.svg'




export const properties = [ 
    {
        id: 1,
        rent: "For Sale",
        image: image1,
        icon1: Icon1,
        icon2: video,
        icon3: Image,
        title: "Real House Luxury Villa",
        Location: location,
        venue: "Victoria Island, Lagos",
        bedroom: bed,
        romm: "6 Bedrooms",
        Toilet: toilet,
        rest: "3 Bathrooms",
        Amount: "3,340,000,000",
        Arrow: arrow,
        Share: share,
        Link: link,
    },
    {
        id: 2,
        rent: "For Rent",
        image: image2,
        icon1: Icon1,
        icon2: video,
        icon3: Image,
        title: "Exquisite Haven Villa",
        Location: location,
        venue: "Festac, Lagos",
        bedroom: bed,
        romm: "5 Bedrooms",
        Toilet: toilet,
        rest: "3 Bathrooms",
        Amount: "4,000,000/1 Year",
        Arrow: arrow,
        Share: share,
        Link: link,
    },
    {
        id: 3,
        rent: "For Sale",
        image: image3,
        icon1: Icon1,
        icon2: video,
        icon3: Image,
        title: "Luxe Palatial Villa",
        Location: location,
        venue: "Gbagada, Lagos",
        bedroom: bed,
        romm: "7 Bedrooms",
        Toilet: toilet,
        rest: "3 Bathrooms",
        Amount: "5,350,000,000",
        Arrow: arrow,
        Share: share,
        Link: link,
    },
    {
        id: 4,
        rent: "For Rent",
        image: image4,
        icon1: Icon1,
        icon2: video,
        icon3: Image,
        title: "Harmony Luxury Villa",
        Location: location,
        venue: "Mushin, Lagos",
        bedroom: bed,
        romm: "4 Bedrooms",
        Toilet: toilet,
        rest: "3 Bathrooms",
        Amount: "4,000,000/1 Year",
        Arrow: arrow,
        Share: share,
        Link: link,
    },
    {
        id: 5,
        rent: "For Rent",
        image: image5,
        icon1: Icon1,
        icon2: video,
        icon3: Image,
        title: "Real House Luxury Villa",
        Location: location,
        venue: "Victoria Island, Lagos",
        bedroom: bed,
        romm: "6 Bedrooms",
        Toilet: toilet,
        rest: "4 Bathrooms",
        Amount: "350,000,000",
        Arrow: arrow,
        Share: share,
        Link: link,
    },
    {
        id: 6,
        rent: "For Sale",
        image: image6,
        icon1: Icon1,
        icon2: video,
        icon3: Image,
        title: "Real House Luxury Villa",
        Location: location,
        venue: "Lekki-Ajah, Lagos",
        bedroom: bed,
        romm: "5 Bedrooms",
        Toilet: toilet,
        rest: "3 Bathrooms",
        Amount: "4,200,000/1 Year",
        Arrow: arrow,
        Share: share,
        Link: link,
    },
    {
        id: 7,
        rent: "For Sale",
        image: image7,
        icon1: Icon1,
        icon2: video,
        icon3: Image,
        title: "Infinite Bliss Villa",
        Location: location,
        venue: "Ishiagu, Enugu",
        bedroom: bed,
        romm: "5 Bedrooms",
        Toilet: toilet,
        rest: "3 Bathrooms",
        Amount: "2,350,000,000",
        Arrow: arrow,
        Share: share,
        Link: link,
    },
    {
        id: 8,
        rent: "For Sale",
        image: image8,
        icon1: Icon1,
        icon2: video,
        icon3: Image,
        title: "Real House Luxury Villa",
        Location: location,
        venue: "Works Layout, Owerri",
        bedroom: bed,
        romm: "8 Bedrooms",
        Toilet: toilet,
        rest: "6 Bathrooms",
        Amount: "3,350,000/1 Year",
        Arrow: arrow,
        Share: share,
        Link: link,
    },
    {
        id: 9,
        rent: "For Rent",
        image: image9,
        icon1: Icon1,
        icon2: video,
        icon3: Image,
        title: "Real House Luxury Villa",
        Location: location,
        venue: "Ikeja, Lagos",
        bedroom: bed,
        romm: "6 Bedrooms",
        Toilet: toilet,
        rest: "6 Bathrooms",
        Amount: "600,000,000",
        Arrow: arrow,
        Share: share,
        Link: link,
    }
]